import { readFile, writeFile } from 'node:fs/promises';

const shell=(title,body,script='')=>`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:Arial,sans-serif;background:#eef5f0;color:#17382a;margin:0}.wrap{max-width:900px;margin:40px auto;padding:20px}.card{background:#fff;border-radius:18px;padding:22px;box-shadow:0 8px 30px #0001;margin:14px 0}input,select,button{font:inherit;padding:11px;border-radius:10px;border:1px solid #ccd6cf}input,select{width:100%;box-sizing:border-box;margin:6px 0 12px}button,.btn{background:#153d2b;color:#fff;border:0;font-weight:800;cursor:pointer;text-decoration:none;display:inline-block;padding:11px 16px;border-radius:10px}.blue{background:#0d6efd}.red{background:#a32135}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.stat{background:#edf7f0;border-radius:14px;padding:15px}.num{font-size:30px;font-weight:900}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.muted{color:#6a7a70}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:start}@media(max-width:700px){table{font-size:13px}.wrap{margin:10px auto}}</style></head><body><div class="wrap">${body}</div><script>${script}</script></body></html>`;

const login=shell('Classroom Compass Login',`<div class="card"><h1>🔐 Classroom Compass</h1><p>تسجيل دخول المعلم / Teacher Login</p><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><button id="go">دخول / Sign in</button><p id="msg" class="muted"></p></div>`,`
async function go(){msg.textContent='';const r=await fetch('/api/account?action=login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});const j=await r.json();if(r.ok)location.href='/?tools=1';else msg.textContent=j.error||'Login failed'};document.getElementById('go').onclick=go;document.addEventListener('keydown',e=>{if(e.key==='Enter')go()});fetch('/api/account?action=setup-status').then(r=>r.json()).then(j=>{if(j.needsSetup)msg.innerHTML='لم يتم إنشاء المدير بعد. <a href="/setup.html">First admin setup</a>'});`);

const setup=shell('First Admin Setup',`<div class="card"><h1>👑 First Admin Setup</h1><p>تُستخدم مرة واحدة فقط لإنشاء المدير الرئيسي.</p><input id="token" placeholder="Setup token"><input id="name" placeholder="Admin name"><input id="email" type="email" placeholder="Admin email"><input id="password" type="password" placeholder="Password (8+ characters)"><button id="go">Create Admin / إنشاء المدير</button><p id="msg" class="muted"></p></div>`,`
const q=new URLSearchParams(location.search);if(q.get('token'))token.value=q.get('token');document.getElementById('go').onclick=async()=>{const r=await fetch('/api/account?action=setup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({setupToken:token.value,name:name.value,email:email.value,password:password.value})});const j=await r.json();if(r.ok)location.href='/admin.html';else msg.textContent=j.error||'Setup failed'};`);

const admin=shell('Classroom Compass Admin',`<div class="row"><div><h1>⚙️ Admin Dashboard</h1><div class="muted">إدارة حسابات المعلمين والصلاحيات</div></div><div style="margin-inline-start:auto"><a class="btn" href="/?tools=1">Classroom Tools</a> <button id="logout" class="red">Logout</button></div></div><div class="grid"><div class="stat">الحسابات<div class="num" id="total">0</div></div><div class="stat">النشطة<div class="num" id="active">0</div></div><div class="stat">Teachers<div class="num" id="teachers">0</div></div><div class="stat">Admins<div class="num" id="admins">0</div></div><div class="stat">Viewers<div class="num" id="viewers">0</div></div></div><div class="card"><h2>➕ إنشاء حساب</h2><div class="grid"><input id="name" placeholder="Name"><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Temporary password"><select id="role"><option value="teacher">Teacher</option><option value="viewer">Viewer</option><option value="admin">Admin</option></select></div><button id="create">Create account</button><p id="msg" class="muted"></p></div><div class="card"><h2>👥 Accounts</h2><div id="users"></div></div>`,`
let me=null;async function api(action,opt={}){const r=await fetch('/api/account?action='+action,opt);if(r.status===401){location.href='/login.html';throw 0}const j=await r.json();if(!r.ok)throw new Error(j.error||'Error');return j}async function load(){const m=await api('me');me=m.user;if(me.role!=='admin'){location.href='/?tools=1';return}const s=await api('stats');['total','active','teachers','admins','viewers'].forEach(k=>document.getElementById(k).textContent=s[k]);const u=await api('users');users.innerHTML='<table><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Change</th></tr>'+u.users.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.email)+'</td><td>'+x.role+'</td><td>'+(x.active?'Active':'Disabled')+'</td><td><select data-role="'+x.id+'"><option '+(x.role==='teacher'?'selected':'')+' value="teacher">Teacher</option><option '+(x.role==='viewer'?'selected':'')+' value="viewer">Viewer</option><option '+(x.role==='admin'?'selected':'')+' value="admin">Admin</option></select> <button data-toggle="'+x.id+'" data-active="'+x.active+'">'+(x.active?'Disable':'Enable')+'</button></td></tr>').join('')+'</table>';document.querySelectorAll('[data-role]').forEach(e=>e.onchange=()=>patch(e.dataset.role,{role:e.value}));document.querySelectorAll('[data-toggle]').forEach(e=>e.onclick=()=>patch(e.dataset.toggle,{active:e.dataset.active!=='true'}))}function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}async function patch(id,data){await api('users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...data})});load()}create.onclick=async()=>{try{await api('users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:name.value,email:email.value,password:password.value,role:role.value})});msg.textContent='✓ Account created';name.value=email.value=password.value='';load()}catch(e){msg.textContent=e.message}};logout.onclick=async()=>{await fetch('/api/account?action=logout',{method:'POST'});location.href='/login.html'};load();`);

await writeFile('dist/login.html',login,'utf8');
await writeFile('dist/setup.html',setup,'utf8');
await writeFile('dist/admin.html',admin,'utf8');

for (const file of ['dist/index.html','dist/offline.html']) {
  let html=await readFile(file,'utf8');
  html=html.replace('</head>',`<style>#ccUserBar{position:fixed;left:12px;top:10px;z-index:99999;background:#fff;border:1px solid #d7e1da;border-radius:999px;padding:7px 11px;font:700 12px Arial;box-shadow:0 4px 14px #0001}#ccSoundBox{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:8px}#ccSoundBox button{padding:6px 9px;border-radius:999px;border:0;background:#f0f5f1;cursor:pointer;font-weight:800}</style></head>`);
  html=html.replace('</body>',`<script>
(async()=>{let me;try{const r=await fetch('/api/account?action=me',{credentials:'same-origin'});if(!r.ok){location.href='/login.html';return}me=(await r.json()).user}catch{location.href='/login.html';return}const bar=document.createElement('div');bar.id='ccUserBar';bar.innerHTML='👤 '+(me.name||me.email)+' · '+me.role+(me.role==='admin'?' · <a href="/admin.html">Admin</a>':'');document.body.appendChild(bar);try{const r=await fetch('/api/account?action=data');if(r.ok){const cloud=(await r.json()).data;if(cloud&&Array.isArray(cloud.classes)&&cloud.classes.length&&typeof db!=='undefined'){db=cloud;if(typeof normalize==='function')normalize();if(typeof persist==='function')persist();if(typeof renderAll==='function')renderAll();if(typeof loadCurrent==='function')loadCurrent()}}}catch(e){console.warn('Cloud load',e)}if(me.role==='viewer'){document.querySelectorAll('button,input,select,textarea').forEach(el=>{if(!el.closest('#ccQuickBar'))el.disabled=true});const n=document.createElement('div');n.textContent='Viewer mode • عرض فقط';n.style='position:fixed;top:48px;left:12px;z-index:99999;background:#fff3cd;padding:6px 10px;border-radius:9px;font-weight:800';document.body.appendChild(n)}else{let busy=false;setInterval(async()=>{if(busy||typeof db==='undefined')return;busy=true;try{await fetch('/api/account?action=data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({data:db})})}catch{}busy=false},5000)}
function tone(kind){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A();const g=c.createGain();g.connect(c.destination);g.gain.setValueAtTime(.12,c.currentTime);if(kind==='clap'){const b=c.createBuffer(1,c.sampleRate*.18,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const s=c.createBufferSource();s.buffer=b;s.connect(g);s.start();return}const seq=kind==='cheer'?[523,659,784]:[660,880];seq.forEach((f,i)=>{const o=c.createOscillator();o.type='sine';o.frequency.value=f;o.connect(g);o.start(c.currentTime+i*.12);o.stop(c.currentTime+i*.12+.16)})}
const box=document.createElement('div');box.id='ccSoundBox';box.innerHTML='<b>🔊 Motivation:</b><button data-s="chime">✨ Chime</button><button data-s="cheer">🎉 Cheer</button><button data-s="clap">👏 Clap</button>';const p=document.getElementById('phrase')||document.querySelector('main');if(p)p.insertAdjacentElement('afterend',box);box.querySelectorAll('button').forEach(b=>b.onclick=()=>tone(b.dataset.s));document.addEventListener('click',e=>{if(e.target.closest?.('.ccRe')||e.target.id==='excellentBtn')tone('chime')});
})();
</script></body>`);
  await writeFile(file,html,'utf8');
}
console.log('Added account UI, cloud sync, roles, and motivation sounds.');
